#ifndef SCREENSTATES_H_
#define SCREENSTATES_H_

typedef enum ScreenEnum {
  SCREEN_LOCKED_DIMMED,
  SCREEN_LOCKED_ACTIVE,
  SCREEN_DEVICE_GROUP,
  SCREEN_ORDER,
  SCREEN_SERVICE,
} ScreenState_TypeDef;

#endif  // SCREENSTATES_H_